/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { notFound } from 'next/navigation';
import Header from './Header';
import { direction } from '@/lib/design';
import { translations } from '@/lib/translations';
import { PARTNERS } from '@/lib/constants/partners';
import { isLanguage, localizedPath, type Language } from '@/lib/i18n';

const A = () => <span className="arrow" aria-hidden="true">↗</span>;
const Star = ({ size = 38 }: { size?: number }) => <img src="/favicon.svg" alt="" width={size} height={size} />;
const sections = [
  { slug: 'life-sciences', key: 'lifesciences', title: 'Life Sciences', image: '/lifesciences.jpg', partner: 0, fr: 'Accompagner ceux qui font avancer la santé.', en: 'Supporting those who move healthcare forward.' },
  { slug: 'industry', key: 'manufacturing', title: 'Industrie', image: '/industry.jpg', partner: 1, fr: 'Faire grandir les savoir-faire et les entreprises.', en: 'Growing industrial expertise and businesses.' },
  { slug: 'private-equity', key: 'privateEquity', title: 'Private Equity', image: '/pe.jpg', partner: 2, fr: 'Mettre le leadership au cœur de la création de valeur.', en: 'Putting leadership at the heart of value creation.' },
  { slug: 'ceo-search', key: 'ceoSearch', title: 'CEO Search', image: '/ceosearch.jpg', partner: 0, fr: 'Le choix qui ouvre le prochain chapitre.', en: 'The decision that opens the next chapter.' },
] as const;
type Intro = string | readonly string[] | { type: string; title: string; content: string };
const title = (item: typeof sections[number], lang: Language) => item.slug === 'industry' && lang === 'en' ? 'Industry' : item.title;
const href = (path: string, lang: Language) => localizedPath(path, lang);
const isAtelier = direction === 'atelier';
const isSignal = direction === 'signal';
const isHorizon = direction === 'horizon';

function Footer({ lang }: { lang: Language }) {
  return <footer className="footer-line wrap"><span>© {new Date().getFullYear()} PITKER. {lang === 'fr' ? 'L’art & la manière.' : 'Skill and art.'}</span><div className="footer-links"><Link href={href('/contact', lang)}>Contact</Link><a href="https://www.linkedin.com/company/pitker" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><Link href={href('/mentions-legales', lang)}>{lang === 'fr' ? 'Mentions légales' : 'Legal notice'}</Link></div></footer>;
}
function ContactCTA({ lang }: { lang: Language }) {
  const fr = lang === 'fr';
  if (isAtelier) return <section className="a-contact wrap"><p className="label">{fr ? 'La suite commence par une conversation.' : 'The next chapter starts with a conversation.'}</p><div className="a-contact-top"><h2>{fr ? 'Et si l’on' : 'Let’s make'}<br/><em>{fr ? 'se rencontrait ?' : 'a connection.'}</em></h2><Link className="round-link" href={href('/contact',lang)} aria-label={fr ? 'Contacter PITKER' : 'Contact PITKER'}>↗</Link></div><div className="a-contact-bottom"><Link className="text-link" href={href('/contact',lang)}>{fr ? 'Parlons de votre prochain chapitre' : 'Let’s talk about your next chapter'} <A/></Link><p>143 boulevard Haussmann<br/>75008 Paris, France</p></div></section>;
  if (isSignal) return <section className="s-contact wrap"><p className="label">{fr ? 'Le prochain mouvement commence ici.' : 'Your next move starts here.'}</p><h2>{fr ? <>ON FAIT<br/>BOUGER<br/>LA SUITE ↗</> : <>LET’S MAKE<br/>THE NEXT<br/>MOVE ↗</>}</h2><div className="s-contact-bottom"><p>{fr ? 'Votre ambition. Notre prochain défi.' : 'Your ambition. Our next challenge.'}<br/><span className="small-copy">143 boulevard Haussmann, Paris.</span></p><Link className="s-cta" href={href('/contact',lang)}>{fr ? 'Faisons connaissance' : 'Let’s get acquainted'} <A/></Link></div></section>;
  return <section className="h-contact"><div className="h-rings" aria-hidden="true"><i/><i/><i/><i/></div><div className="wrap"><p className="label">{fr ? 'Et maintenant, votre prochain cap.' : 'Now, your next horizon.'}</p><h2>{fr ? <>Ouvrons<br/>de nouvelles<br/><em>perspectives.</em></> : <>Let’s open<br/>new<br/><em>perspectives.</em></>}</h2><div className="h-contact-bottom"><Link className="text-link" href={href('/contact',lang)}>{fr ? 'Commençons par un échange' : 'Let’s start a conversation'} <A/></Link><p>143 boulevard Haussmann<br/>75008 Paris, France</p></div></div></section>;
}
function Partners({ lang, full = false }: { lang: Language; full?: boolean }) {
  const fr = lang === 'fr';
  return <div className={`partner-grid ${full ? 'partner-grid-full' : ''}`}>{PARTNERS.map(p => <article className="partner-card" key={p.id} id={`partner-${p.id}`}>
    <Link href={href(`/people#partner-${p.id}`,lang)} aria-label={fr ? `Découvrir ${p.name}` : `Meet ${p.name}`}><div className="partner-portrait"><img src={p.imageOff} width="500" height="625" loading="lazy" alt={p.name}/></div></Link>
    <h3>{p.name}</h3><p>{p.role[lang]} · {p.major[lang]}</p>
    {full ? <><div className="partner-bio">{p.biography[lang].split('\n\n').map((paragraph,i)=><p key={i}>{paragraph}</p>)}</div><div className="partner-links"><a href={`mailto:${p.email}`}>{fr ? 'Écrire' : 'Email'} <A/></a><a href={p.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn <A/></a></div></> : <Link className="text-link" href={href(`/people#partner-${p.id}`,lang)}>{fr ? 'Rencontrer' : 'Meet'} <A/></Link>}
  </article>)}</div>;
}
function TeamTeaser({lang}:{lang:Language}) {
 const fr=lang==='fr';
 return <section className={isAtelier?'a-team':isSignal?'s-team':'h-team'}><div className="wrap"><div className="section-top"><div><p className="label section-label">{fr?'03 / Une rencontre, d’abord':'03 / A human connection'}</p><h2>{isAtelier ? (fr?<>Des personnalités.<br/><em>Une même exigence.</em></>:<>Distinct personalities.<br/><em>Shared standards.</em></>) : isSignal ? (fr?<>Pas des profils.<br/>Des personnalités.</>:<>Not just profiles.<br/>Personalities.</>) : (fr?<>Une relation de confiance.<br/>Un engagement personnel.</>:<>A trusted relationship.<br/>A personal commitment.</>)}</h2></div><p>{fr?'Trois associés directement engagés à vos côtés. Des regards complémentaires, une approche sur mesure.':'Three partners personally committed to your success. Complementary perspectives and a tailored approach.'}</p></div><Partners lang={lang}/></div></section>;
}
function Practices({lang,heading=true}:{lang:Language;heading?:boolean}) {
 const fr=lang==='fr';
 return <section className={`${isAtelier?'a-practices':isSignal?'s-practices':'h-expertise'} wrap`} id="expertises">
  {heading&&<div className="section-top"><div><p className="label section-label">{fr?'02 / Nos territoires':'02 / Our expertise'}</p><h2>{isAtelier?(fr?<>La connaissance du terrain.<br/><em>Le sens de l’essentiel.</em></>:<>A deep understanding.<br/><em>A clear perspective.</em></>):isSignal?(fr?<>Du terrain.<br/>Du flair. De l’impact.</>:<>Insight.<br/>Instinct. Impact.</>):(fr?<>Comprendre votre monde.<br/>Éclairer la suite.</>:<>Understand your world.<br/>Illuminate what’s next.</>)}</h2></div><p>{fr?'Une connaissance concrète de vos métiers et de ceux qui les font avancer.':'A deep understanding of your business and the people who move it forward.'}</p></div>}
  {isAtelier ? sections.map((s,i)=><div className="a-practice" key={s.slug}><Link className="a-practice-row" href={href(`/practices/${s.slug}`,lang)}><span className="label">0{i+1}</span><h3>{title(s,lang)}</h3><p>{s[lang]}</p><A/></Link></div>) : isSignal ? <div className="s-practice-grid">{sections.map((s,i)=><Link className="s-practice" href={href(`/practices/${s.slug}`,lang)} key={s.slug}><div className="label"><span>0{i+1} / {title(s,lang)}</span><A/></div><div className={`shape ${['shape-circles','shape-grid','shape-orbit','shape-stairs'][i]}`} aria-hidden="true"/><div><h3>{title(s,lang)}.</h3><p>{s[lang]}</p></div></Link>)}</div> : <><div className="h-sector-list">{sections.slice(0,3).map((s,i)=><Link className="h-sector" href={href(`/practices/${s.slug}`,lang)} key={s.slug}><img src={s.image} width="600" height="800" loading="lazy" alt=""/><div className="label"><span>0{i+1} / {title(s,lang)}</span><A/></div><div><h3>{title(s,lang)}</h3><p>{s[lang]}</p></div></Link>)}</div><Link className="h-ceo" href={href('/practices/ceo-search',lang)}><h3>CEO Search</h3><p>{fr?'Une expertise transversale pour les décisions qui engagent l’avenir.':'Cross-sector expertise for the decisions that shape the future.'}</p><A/></Link></>}
 </section>;
}
function HomeHero({lang}:{lang:Language}) {
 const fr=lang==='fr';
 if(isAtelier)return <section className="a-hero wrap"><div className="a-hero-top"><span className="label">{fr?'Boutique d’executive search':'Executive search boutique'}</span><span className="label">Paris · France & international</span></div><div className="a-hero-grid"><div className="a-hero-copy reveal"><h1>{fr?<>L’art de<br/>choisir.<br/><em>L’humain.</em></>:<>The art of<br/>finding<br/><em>people.</em></>}</h1><p>{fr?'Derrière chaque trajectoire d’entreprise, il y a une rencontre décisive. Nous sommes là pour la rendre possible.':'Behind every company’s journey is a defining encounter. We are here to make it happen.'}</p><Link className="text-link" href={href('/what-we-do',lang)}>{fr?'L’art & la manière PITKER':'The PITKER approach'} <A/></Link></div><figure className="a-art reveal delay"><img src="/design/atelier.png" width="1122" height="1402" alt={fr?'Sculpture rouge PITKER dans une galerie blanche':'PITKER red sculpture in a white gallery'} fetchPriority="high"/><figcaption>{fr?'LA JUSTESSE D’UNE RENCONTRE':'THE RIGHT CONNECTION'}</figcaption></figure></div><div className="a-hero-bottom"><span>Executive search & leadership advisory</span><span>{fr?'Indépendants par conviction. Engagés par nature.':'Independent by conviction. Committed by nature.'}</span><a href="#conviction" aria-label={fr?'Découvrir notre conviction':'Explore our perspective'}>↓</a></div></section>;
 if(isSignal)return <><section className="s-hero wrap"><div className="s-hero-top label"><span>Executive search. Human first.</span><span>Paris / France / International</span></div><h1 className="s-title reveal"><span className="s-line">{fr?'LE BON':'RIGHT'} <span className="s-glyph" aria-hidden="true"><Star size={213}/></span></span><span className="s-line outline">{fr?'TALENT.':'PEOPLE.'}</span><span className="s-line">{fr?'LE DÉCLIC.':'REAL IMPACT.'}</span></h1><div className="s-hero-bottom reveal delay"><span className="s-caption">{fr?<>LES ENTREPRISES BOUGENT.<br/>LES BONNES PERSONNES LES FONT AVANCER.</>:<>BUSINESSES MOVE.<br/>THE RIGHT PEOPLE MOVE THEM FORWARD.</>}</span><p>{fr?'Nous connectons les entreprises ambitieuses aux dirigeants qui feront la différence.':'We connect ambitious businesses with the leaders who will make a difference.'}</p><Link className="s-cta" href={href('/practices',lang)}>{fr?'Trouvons votre prochain déclic':'Find your next catalyst'} <A/></Link></div></section><div className="s-ticker">{sections.map(s=><span className="ticker-item" key={s.slug}>{title(s,lang).toUpperCase()} <Star size={22}/></span>)}</div></>;
 return <><div className="h-hero wrap"><p className="label"><span className="h-dot" aria-hidden="true"/>Executive search & leadership advisory</p><h1 className="reveal">{fr?<>Le prochain<br/>cap est <em>humain.</em></>:<>The next horizon<br/>is <em>human.</em></>}</h1><div className="h-hero-detail reveal delay"><p>{fr?'Voir au-delà d’un parcours. Reconnaître un potentiel. Trouver les dirigeants qui ouvrent de nouvelles perspectives.':'Look beyond a career. Recognise potential. Find the leaders who open new perspectives.'}</p><Link className="text-link" href={href('/what-we-do',lang)}>{fr?'Une autre perspective':'A different perspective'} <A/></Link></div><span className="h-coordinate" aria-hidden="true">48° 52′ N / 2° 19′ E — PARIS</span></div><div className="h-hero-foot wrap"><span>{fr?'UN CABINET INDÉPENDANT. UN REGARD ENGAGÉ.':'AN INDEPENDENT FIRM. A COMMITTED PERSPECTIVE.'}</span><span>PARIS · FRANCE & INTERNATIONAL</span><a href="#conviction">{fr?'EXPLORER':'EXPLORE'} ↓</a></div></>;
}
function Home({lang}:{lang:Language}) {
 const fr=lang==='fr';
 return <>{!isHorizon&&<Header lang={lang} path="/" dark={isSignal}/>}<main id="main">{isHorizon?<div className="h-cinema"><img className="h-backdrop" src="/design/horizon.png" width="1672" height="941" alt="" fetchPriority="high"/><Header lang={lang} path="/" dark/><HomeHero lang={lang}/></div>:<HomeHero lang={lang}/>}
 {isSignal?<section className="s-manifesto" id="conviction"><div className="wrap"><div className="s-manifesto-grid"><p className="label">{fr?'01 / Notre point de vue':'01 / Our perspective'}</p><h2>{fr?<>Les CV racontent<br/>le passé.<br/><span>Nous cherchons<br/>ce qui vient après.</span></>:<>CVs tell you<br/>the past.<br/><span>We look for<br/>what comes next.</span></>}</h2></div><div className="s-stats">{translations[lang].whatWeDo.keyStats.stats.filter((_,i)=>[1,2,4].includes(i)).map(s=><div className="s-stat" key={s.number}><strong>{s.number}</strong><span>{s.description}</span></div>)}</div></div></section>:<section className={`${isAtelier?'a-intro':'h-intro'} wrap`} id="conviction"><div><p className="label">{fr?'01 / Notre conviction':'01 / Our conviction'}</p>{isAtelier&&<div className="a-star"><Star/></div>}</div><div><h2>{isAtelier?(fr?<>Un dirigeant ne se résume<br/>pas à un parcours.<br/><em>Une rencontre non plus.</em></>:<>A leader is more<br/>than a career.<br/><em>A connection is, too.</em></>):(fr?<>Les grandes trajectoires<br/>commencent par<br/><span>les bonnes rencontres.</span></>:<>Great journeys<br/>begin with<br/><span>the right connections.</span></>)}</h2><p>{fr?'Comprendre une culture, saisir une ambition, reconnaître une personnalité. Chez PITKER, nous réunissons l’exigence de la recherche et la finesse du regard pour accompagner les décisions qui engagent votre avenir.':'Understanding a culture, grasping an ambition, recognising a personality. At PITKER, we combine rigorous search with perceptive judgement to support the decisions that shape your future.'}</p><Link className="text-link" href={href('/what-we-do',lang)}>{fr?'Découvrir le cabinet':'Meet the firm'} <A/></Link></div></section>}
 <Practices lang={lang}/><TeamTeaser lang={lang}/><ContactCTA lang={lang}/></main><Footer lang={lang}/></>;
}
function InteriorHero({lang,eyebrow,heading,lead,image}:{lang:Language;eyebrow:string;heading:string;lead?:string;image?:string}) {
 return <section className={`interior-head ${image?'has-image':''}`}><div className="wrap interior-head-grid"><div><Link className="label breadcrumb" href={href('/',lang)}>{lang==='fr'?'Accueil':'Home'} / {eyebrow}</Link><h1>{heading}</h1>{lead&&<p className="interior-lead">{lead}</p>}</div>{image?<figure className="interior-image"><img src={image} width="800" height="900" alt="" fetchPriority="high"/></figure>:<div className="interior-star" aria-hidden="true"><Star size={213}/></div>}</div></section>;
}
function BodyParagraphs({items}:{items:readonly Intro[]}) { return <>{items.map((item,i)=>typeof item==='string'?<p key={i}>{item}</p>:'title' in item?<section key={i}><h2>{item.title}</h2><p>{item.content}</p></section>:<ul key={i}>{item.map((t,j)=><li key={j}>{t}</li>)}</ul>)}</>; }
function About({lang}:{lang:Language}) {
 const t=translations[lang].whatWeDo,fr=lang==='fr';
 return <><InteriorHero lang={lang} eyebrow={fr?'Le cabinet':'The firm'} heading={isAtelier?(fr?'L’art & la manière.':'Skill and art.'):isSignal?(fr?'INDÉPENDANTS. ENGAGÉS.':'INDEPENDENT. COMMITTED.'):(fr?'Un autre regard.':'A different perspective.')} lead={fr?'La proximité d’une boutique. La profondeur de trois expertises. Un engagement personnel.':'The personal touch of a boutique. The depth of three specialisms. A personal commitment.'} image={isAtelier?'/design/atelier.png':isHorizon?'/design/horizon.png':undefined}/><section className="reading-section wrap"><aside><p className="label">PITKER / {fr?'Depuis 2020':'Since 2020'}</p><Star/></aside><div className="prose"><BodyParagraphs items={t.hero.description.split('\n\n')}/></div></section><section className="numbers-band"><div className="wrap"><p className="label">{t.keyStats.title}</p><div className="numbers-grid">{t.keyStats.stats.map(s=><div key={s.number}><strong>{s.number}</strong><p>{s.description}</p></div>)}</div></div></section><TeamTeaser lang={lang}/></>;
}
function People({lang}:{lang:Language}) {
 const fr=lang==='fr';
 return <><InteriorHero lang={lang} eyebrow={fr?'Les associés':'Our partners'} heading={isAtelier?(fr?'Des personnalités. Une même exigence.':'Distinct personalities. Shared standards.'):isSignal?(fr?'LE COLLECTIF.':'THE COLLECTIVE.'):(fr?'Des regards qui se complètent.':'Complementary perspectives.')} lead={fr?'Jean-Marie Verdier, Maud Chabert et Patrice de Fournas. Trois parcours, une même attention portée à l’humain.':'Jean-Marie Verdier, Maud Chabert and Patrice de Fournas. Three journeys, one shared focus on people.'}/><section className="people-intro wrap"><p>{translations[lang].people.partners.description}</p></section><section className="people-section wrap"><Partners lang={lang} full/></section></>;
}
function PracticeDetail({lang,slug}:{lang:Language;slug:string}) {
 const item=sections.find(s=>s.slug===slug);if(!item)notFound();
 const t=translations[lang].practices[item.key];const fr=lang==='fr';const partner=PARTNERS[item.partner];
 return <><InteriorHero lang={lang} eyebrow={fr?'Expertises':'Expertise'} heading={title(item,lang)} lead={item[lang]} image={item.image}/><section className="reading-section wrap"><aside><p className="label">{fr?'Notre perspective':'Our perspective'}</p><div className="practice-nav">{sections.map(s=><Link key={s.slug} href={href(`/practices/${s.slug}`,lang)} aria-current={s.slug===slug?'page':undefined}>{title(s,lang)} <A/></Link>)}</div></aside><div className="prose"><BodyParagraphs items={t.intro}/></div></section><section className="strengths-section"><div className="wrap"><div className="section-top"><h2>{t.strengths.title}</h2><p>{fr?'Une expertise qui se traduit dans chaque recherche.':'Expertise that informs every search.'}</p></div><div className="strengths-grid">{t.strengths.points.map((p,i)=><article key={p.title}><span className="label">0{i+1}</span><h3>{p.title}</h3><p>{p.description}</p></article>)}</div></div></section><section className="practice-contact wrap"><div><p className="label">{fr?'Votre interlocuteur':'Your contact'}</p><h2>{partner.name}</h2><p>{partner.role[lang]} · {partner.major[lang]}</p><Link className="text-link" href={href(`/people#partner-${partner.id}`,lang)}>{fr?'Découvrir son parcours':'Discover their background'} <A/></Link><a className="text-link" href={`mailto:${partner.email}`}>{fr?'Entrer en relation':'Get in touch'} <A/></a></div><img src={partner.imageOff} alt={partner.name} width="400" height="440" loading="lazy"/></section></>;
}
function Contact({lang}:{lang:Language}) {
 const fr=lang==='fr';
 return <><InteriorHero lang={lang} eyebrow="Contact" heading={isAtelier?(fr?'Commençons par une rencontre.':'Let’s start with a connection.'):isSignal?(fr?'ON EN PARLE ?':'LET’S TALK.'):(fr?'Votre prochain cap commence ici.':'Your next horizon starts here.')} lead={translations[lang].contact.hero.description}/><section className="contact-section wrap"><div className="contact-note"><p className="label">{fr?'Une relation directe':'A direct relationship'}</p><h2>{fr?'À votre écoute.':'Here to listen.'}</h2><p>{fr?'Un recrutement stratégique, une réflexion sur votre équipe ou votre parcours : contactez directement l’un de nos associés.':'A strategic appointment, a question about your team or your own career: contact one of our partners directly.'}</p></div><div className="contact-list">{PARTNERS.map(p=><article key={p.id}><img src={p.imageSmall} alt={p.name} width="88" height="88"/><div><h3>{p.name}</h3><p>{p.major[lang]}</p><a href={`mailto:${p.email}`}>{p.email} <A/></a></div></article>)}</div></section><section className="office-section"><div className="wrap office-grid"><div><p className="label">{fr?'Notre adresse':'Our address'} / Paris</p><h2>143 boulevard<br/>Haussmann.</h2><p>75008 Paris, France</p><a className="text-link" href="https://www.google.com/maps/search/?api=1&query=143%20boulevard%20Haussmann%2075008%20Paris" target="_blank" rel="noopener noreferrer">{fr?'Ouvrir dans Google Maps':'Open in Google Maps'} <A/></a></div><div className="office-art" aria-hidden="true"><div className="street street-one"/><div className="street street-two"/><div className="street street-three"/><div className="office-marker"><Star size={52}/><span>PITKER</span></div><span className="office-coordinate">48° 52′ N / 2° 19′ E</span></div></div></section></>;
}
function Legal({lang}:{lang:Language}) {
 const t=translations[lang].legal;
 return <><InteriorHero lang={lang} eyebrow={t.title} heading={t.title}/><section className="legal-section wrap prose">{Object.entries(t.sections).map(([key,value])=><section key={key}><h2>{value.title}</h2>{Object.entries(value).filter(([k])=>k!=='title').map(([k,v])=>Array.isArray(v)?<ul key={k}>{v.map((x,i)=><li key={i}>{String(x)}</li>)}</ul>:<p key={k}>{String(v)}</p>)}</section>)}</section></>;
}
export default async function Site({params,path}:{params:Promise<{lang:string}>;path:string}) {
 const {lang}=await params;if(!isLanguage(lang))notFound();
 if(path==='/')return <Home lang={lang}/>;
 return <><Header lang={lang} path={path} dark={!isAtelier}/><main id="main">{path==='/what-we-do'?<About lang={lang}/>:path==='/people'?<People lang={lang}/>:path==='/contact'?<Contact lang={lang}/>:path==='/mentions-legales'?<Legal lang={lang}/>:path==='/practices'?<><InteriorHero lang={lang} eyebrow={lang==='fr'?'Expertises':'Expertise'} heading={lang==='fr'?'Des univers. Une même exigence.':'Distinct worlds. Shared standards.'} lead={lang==='fr'?'Life Sciences, Industrie, Private Equity et CEO Search. Des expertises ciblées pour vos décisions les plus importantes.':'Life Sciences, Industry, Private Equity and CEO Search. Focused expertise for your most important decisions.'}/><Practices lang={lang} heading={false}/></>:<PracticeDetail lang={lang} slug={path.split('/').at(-1)!}/>}{!['/contact','/mentions-legales'].includes(path)&&<ContactCTA lang={lang}/>}</main><Footer lang={lang}/></>;
}
